language: php

php:
  - 5.4

script: phpunit --configuration phpunit.travis.xml ./tests/com/mohiva/test/pyramid

before_install:
  git submodule init && git submodule --quiet update

notifications:
  email:
    - travis.mohiva.pyramid@mohiva.com
